// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: proto/shop.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListBananasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ListBananasRequest) Reset() {
	*x = ListBananasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBananasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBananasRequest) ProtoMessage() {}

func (x *ListBananasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBananasRequest.ProtoReflect.Descriptor instead.
func (*ListBananasRequest) Descriptor() ([]byte, []int) {
	return file_proto_shop_proto_rawDescGZIP(), []int{0}
}

func (x *ListBananasRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListBananasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bananas []*Banana `protobuf:"bytes,1,rep,name=bananas,proto3" json:"bananas,omitempty"`
}

func (x *ListBananasResponse) Reset() {
	*x = ListBananasResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBananasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBananasResponse) ProtoMessage() {}

func (x *ListBananasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBananasResponse.ProtoReflect.Descriptor instead.
func (*ListBananasResponse) Descriptor() ([]byte, []int) {
	return file_proto_shop_proto_rawDescGZIP(), []int{1}
}

func (x *ListBananasResponse) GetBananas() []*Banana {
	if x != nil {
		return x.Bananas
	}
	return nil
}

type GetBananaColorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BananaId string `protobuf:"bytes,1,opt,name=banana_id,json=bananaId,proto3" json:"banana_id,omitempty"`
}

func (x *GetBananaColorRequest) Reset() {
	*x = GetBananaColorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shop_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBananaColorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBananaColorRequest) ProtoMessage() {}

func (x *GetBananaColorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBananaColorRequest.ProtoReflect.Descriptor instead.
func (*GetBananaColorRequest) Descriptor() ([]byte, []int) {
	return file_proto_shop_proto_rawDescGZIP(), []int{2}
}

func (x *GetBananaColorRequest) GetBananaId() string {
	if x != nil {
		return x.BananaId
	}
	return ""
}

type GetBananaColorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color string `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *GetBananaColorResponse) Reset() {
	*x = GetBananaColorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shop_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBananaColorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBananaColorResponse) ProtoMessage() {}

func (x *GetBananaColorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBananaColorResponse.ProtoReflect.Descriptor instead.
func (*GetBananaColorResponse) Descriptor() ([]byte, []int) {
	return file_proto_shop_proto_rawDescGZIP(), []int{3}
}

func (x *GetBananaColorResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type Banana struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Color string `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *Banana) Reset() {
	*x = Banana{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shop_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Banana) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banana) ProtoMessage() {}

func (x *Banana) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shop_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banana.ProtoReflect.Descriptor instead.
func (*Banana) Descriptor() ([]byte, []int) {
	return file_proto_shop_proto_rawDescGZIP(), []int{4}
}

func (x *Banana) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Banana) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

var File_proto_shop_proto protoreflect.FileDescriptor

var file_proto_shop_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x28, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x6e, 0x61, 0x6e, 0x61,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x38, 0x0a, 0x13,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x6e, 0x61, 0x6e, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x07, 0x62, 0x61, 0x6e, 0x61, 0x6e, 0x61, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x42, 0x61, 0x6e, 0x61, 0x6e, 0x61, 0x52, 0x07, 0x62,
	0x61, 0x6e, 0x61, 0x6e, 0x61, 0x73, 0x22, 0x34, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e,
	0x61, 0x6e, 0x61, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x61, 0x6e, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x61, 0x6e, 0x61, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x61, 0x6e, 0x61, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x2e, 0x0a, 0x06,
	0x42, 0x61, 0x6e, 0x61, 0x6e, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x32, 0x83, 0x01, 0x0a,
	0x04, 0x53, 0x68, 0x6f, 0x70, 0x12, 0x38, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x6e,
	0x61, 0x6e, 0x61, 0x73, 0x12, 0x13, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x6e, 0x61, 0x6e,
	0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x61, 0x6e, 0x61, 0x6e, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x41, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x61, 0x6e, 0x61, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x12, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x61, 0x6e, 0x61, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x42,
	0x61, 0x6e, 0x61, 0x6e, 0x61, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6a, 0x6f, 0x73, 0x65, 0x6e, 0x61, 0x72, 0x76, 0x61, 0x65, 0x7a, 0x70, 0x2f, 0x63, 0x68,
	0x61, 0x74, 0x2d, 0x67, 0x70, 0x74, 0x2d, 0x73, 0x68, 0x6f, 0x70, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_shop_proto_rawDescOnce sync.Once
	file_proto_shop_proto_rawDescData = file_proto_shop_proto_rawDesc
)

func file_proto_shop_proto_rawDescGZIP() []byte {
	file_proto_shop_proto_rawDescOnce.Do(func() {
		file_proto_shop_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_shop_proto_rawDescData)
	})
	return file_proto_shop_proto_rawDescData
}

var file_proto_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_shop_proto_goTypes = []interface{}{
	(*ListBananasRequest)(nil),     // 0: ListBananasRequest
	(*ListBananasResponse)(nil),    // 1: ListBananasResponse
	(*GetBananaColorRequest)(nil),  // 2: GetBananaColorRequest
	(*GetBananaColorResponse)(nil), // 3: GetBananaColorResponse
	(*Banana)(nil),                 // 4: Banana
}
var file_proto_shop_proto_depIdxs = []int32{
	4, // 0: ListBananasResponse.bananas:type_name -> Banana
	0, // 1: Shop.ListBananas:input_type -> ListBananasRequest
	2, // 2: Shop.GetBananaColor:input_type -> GetBananaColorRequest
	1, // 3: Shop.ListBananas:output_type -> ListBananasResponse
	3, // 4: Shop.GetBananaColor:output_type -> GetBananaColorResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_shop_proto_init() }
func file_proto_shop_proto_init() {
	if File_proto_shop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_shop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBananasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBananasResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shop_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBananaColorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shop_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBananaColorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shop_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Banana); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_shop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shop_proto_goTypes,
		DependencyIndexes: file_proto_shop_proto_depIdxs,
		MessageInfos:      file_proto_shop_proto_msgTypes,
	}.Build()
	File_proto_shop_proto = out.File
	file_proto_shop_proto_rawDesc = nil
	file_proto_shop_proto_goTypes = nil
	file_proto_shop_proto_depIdxs = nil
}
