// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto/shop.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShopClient is the client API for Shop service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShopClient interface {
	ListBananas(ctx context.Context, in *ListBananasRequest, opts ...grpc.CallOption) (*ListBananasResponse, error)
	GetBananaColor(ctx context.Context, in *GetBananaColorRequest, opts ...grpc.CallOption) (*GetBananaColorResponse, error)
}

type shopClient struct {
	cc grpc.ClientConnInterface
}

func NewShopClient(cc grpc.ClientConnInterface) ShopClient {
	return &shopClient{cc}
}

func (c *shopClient) ListBananas(ctx context.Context, in *ListBananasRequest, opts ...grpc.CallOption) (*ListBananasResponse, error) {
	out := new(ListBananasResponse)
	err := c.cc.Invoke(ctx, "/Shop/ListBananas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopClient) GetBananaColor(ctx context.Context, in *GetBananaColorRequest, opts ...grpc.CallOption) (*GetBananaColorResponse, error) {
	out := new(GetBananaColorResponse)
	err := c.cc.Invoke(ctx, "/Shop/GetBananaColor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopServer is the server API for Shop service.
// All implementations must embed UnimplementedShopServer
// for forward compatibility
type ShopServer interface {
	ListBananas(context.Context, *ListBananasRequest) (*ListBananasResponse, error)
	GetBananaColor(context.Context, *GetBananaColorRequest) (*GetBananaColorResponse, error)
	mustEmbedUnimplementedShopServer()
}

// UnimplementedShopServer must be embedded to have forward compatible implementations.
type UnimplementedShopServer struct {
}

func (UnimplementedShopServer) ListBananas(context.Context, *ListBananasRequest) (*ListBananasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBananas not implemented")
}
func (UnimplementedShopServer) GetBananaColor(context.Context, *GetBananaColorRequest) (*GetBananaColorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBananaColor not implemented")
}
func (UnimplementedShopServer) mustEmbedUnimplementedShopServer() {}

// UnsafeShopServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShopServer will
// result in compilation errors.
type UnsafeShopServer interface {
	mustEmbedUnimplementedShopServer()
}

func RegisterShopServer(s grpc.ServiceRegistrar, srv ShopServer) {
	s.RegisterService(&Shop_ServiceDesc, srv)
}

func _Shop_ListBananas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBananasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServer).ListBananas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Shop/ListBananas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServer).ListBananas(ctx, req.(*ListBananasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shop_GetBananaColor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBananaColorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServer).GetBananaColor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Shop/GetBananaColor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServer).GetBananaColor(ctx, req.(*GetBananaColorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Shop_ServiceDesc is the grpc.ServiceDesc for Shop service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Shop_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Shop",
	HandlerType: (*ShopServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBananas",
			Handler:    _Shop_ListBananas_Handler,
		},
		{
			MethodName: "GetBananaColor",
			Handler:    _Shop_GetBananaColor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/shop.proto",
}
